# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", nil) %>

development:
  <<: *default
  database: planning_center_app_development

test:
  <<: *default
  database: planning_center_app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  # When Railway provides DATABASE_URL, Rails will use it.
  # SSL is handled automatically by Railway's DATABASE_URL

cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  # Cable uses the same database as the main app

queue:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  # Queue uses the same database as the main app

cache:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>